apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
spec:
  selector:
    app: tomcat
  ports:
    - protocol: TCP
      nodePort: 31000
      port: 9090
      targetPort: 8080
  type: LoadBalancer